### ISSUE TITLE
`@my/mylib:dev: Error: Can't resolve './src/assets/base.css' in '/Users/foo/bar/packages/my-theme-kit/dist'`

### ISSUE THREAD

**Issue by corysimmons** [MahdiTa97/turborepo-boilerplate#4]
![image](https://user-images.githubusercontent.com/224636/152059270-2e367b4a-29ac-4784-aaae-3fde5617e5b7.png)

The asset css files are empty. I tried adding some simple CSS to them and running `yarn build` from within the `my-theme-kit` dir but it didn't seem to solve it.

**Comment by MahdiTa97** [comment]
@corysimmons you can temporarily add your custom CSS directly in the tailwind.css file.
I removed the CSS assets file.

**Comment by MahdiTa97** [comment]
The bug has been fixed in the v2.0.0 release.
